language: node_js
node_js:
  - '13'

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install --frozen-lockfile

script:
  - yarn build:rollup
  - yarn build:storybook

deploy:
  - provider: pages
    local_dir: storybook-static
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: master
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    edge: true
    on:
      tags: true